name: Run CF Changle

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust and wasm-pack
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-pack
          sudo apt-get install -y binaryen

      - name: Build with wasm-pack (bulk-memory enabled)
        run: |
          echo "[package.metadata.wasm-pack.profile.release]" >> Cargo.toml
          echo "wasm-opt = false" >> Cargo.toml
          RUSTFLAGS="-C target-feature=+bulk-memory" wasm-pack build --release --target web

      - name: Optimize Wasm manually
        run: |
          wasm-opt -O pkg/changli_bg.wasm -o pkg/changli_bg.opt.wasm --enable-bulk-memory

      - name: Publish with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
